<?php
/**
 * @file
 * Contains install and update functions for AMI.
 */
use Drupal\ami\Entity\amiSetEntity;
use Drupal\Core\Language\LanguageInterface;
use Drupal\taxonomy\Entity\Vocabulary;
use Drupal\taxonomy\Entity\Term;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\field\Entity\FieldConfig;
use Drupal\Component\Utility\Environment;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\Core\Database\Database;
use Drupal\Core\Config\Entity\ConfigEntityType;


/**
 * Implements hook_install().
 */

function ami_install() {

}

/**
 * Update 8901 - Create AMI Set entity.
 */
function ami_update_8901() {
  // Code provided by @giancarloby to allow D9 compat.
  $schema = Database::getConnection()->schema();
  if (!$schema->tableExists('ami_setentity')) {
    \Drupal::entityTypeManager()->clearCachedDefinitions();
    \Drupal::entityDefinitionUpdateManager()
      ->installEntityType(\Drupal::entityTypeManager()->getDefinition('ami_set_entity'));
  }
  else {
    return 'AMI Set entity already exists';
  }
}

/**
 * Update 8902 - Add ZIP file Field for AMI Set entity.
 */
function ami_update_8902() {
  $validators = [
    'file_validate_extensions' => ['zip'],
    'file_validate_size' => [Environment::getUploadMaxSize()],
  ];
  $storage_definition = BaseFieldDefinition::create('file')
    ->setLabel(new TranslatableMarkup('Attached ZIP file'))
    ->setDescription(new TranslatableMarkup('A Zip file containing accompanying Files for the Source Data'))
    ->setSetting('file_extensions', 'zip')
    ->setSetting('upload_validators', $validators)
    ->setSetting('uri_scheme', 'private')
    ->setSetting('file_directory', '/ami/zip')
    ->setRequired(FALSE)
    ->setDisplayOptions('view', [
      'label' => 'above',
      'type' => 'file',
      'weight' => -3,
    ])
    ->setDisplayOptions('form', [
      'type' => 'file',
      'description' => [
        'theme' => 'file_upload_help',
        'description' => new TranslatableMarkup('Source Files for this Set')
      ],
      'settings' => [
        'upload_validators' => $validators,
      ],
      'weight' => -3,
    ])
    ->setDisplayConfigurable('view', TRUE)
    ->setDisplayConfigurable('form', TRUE);

  \Drupal::entityDefinitionUpdateManager()->installFieldStorageDefinition('zip_file', 'ami_set_entity', 'ami', $storage_definition);
}

/**
 * Update 8903 - Install Importer Adapter Config Entity.
 */
function ami_update_8903() {
  \Drupal::entityDefinitionUpdateManager()->installEntityType(new ConfigEntityType([
    'id' => 'importeradapter',
    'label' => new TranslatableMarkup('AMI Importer Adapter'),
    'config_prefix' => 'importeradapter',
    'admin_permission' => 'administer site configuration',
    'entity_keys' => [
      'id' => 'id',
      'label' => 'label',
      'uuid' => 'uuid',
    ],
    'config_export' => [
      "id",
      "label",
      "plugin",
      "update_existing",
      "target_entity_types",
      "active",
      "plugin_configuration"
    ],
  ]));
}

/**
 * Update 8903 - Make Private default upload location for ami Set ZIP files.
 */
function ami_update_8904() {
  $field_storage_definition = \Drupal::entityDefinitionUpdateManager()->getFieldStorageDefinition('zip_file', 'ami_set_entity');
  $field_storage_definition->setSetting('uri_scheme', 'private');
  $field_storage_definition->setSetting('file_directory', '/ami/zip');
  \Drupal::entityDefinitionUpdateManager()->updateFieldStorageDefinition($field_storage_definition);
}

/**
 * Update 8905 - Add Report CSV file Field for AMI Set entity.
 */
function ami_update_8905() {
  $validators = [
    'file_validate_extensions' => ['csv'],
    'file_validate_size' => [Environment::getUploadMaxSize()],
  ];

  $storage_definition = BaseFieldDefinition::create('file')
    ->setLabel(t('AMI Process Reports'))
    ->setDescription(t('Processed set report in CSV format'))
    ->setSetting('file_extensions', 'csv')
    ->setSetting('upload_validators', $validators)
    ->setSetting('uri_scheme', 'private')
    ->setSetting('file_directory', '/ami/reports')
    ->setRequired(FALSE)
    ->setDisplayOptions('view', [
      'label' => 'above',
      'type' => 'file',
      'weight' => -2,
    ])
    ->setDisplayConfigurable('view', TRUE)
    ->setDisplayConfigurable('form', TRUE);
  \Drupal::entityDefinitionUpdateManager()->installFieldStorageDefinition('report_file', 'ami_set_entity', 'ami', $storage_definition);
  $field_storage_definition_status = \Drupal::entityDefinitionUpdateManager()->getFieldStorageDefinition('status', 'ami_set_entity');
  $field_storage_definition_status->setLabel(t("This Set's last known status"));
  $field_storage_definition_status->setSetting('allowed_values', amiSetEntity::STATUS);
  $field_storage_definition_status->setSetting('default_value', 'READY');
  \Drupal::entityDefinitionUpdateManager()->updateFieldStorageDefinition($field_storage_definition_status);

  // Update all AMI sets already with 'ready' use the new uppercase default
  $entities_nids = \Drupal::entityQuery('ami_set_entity')
    ->condition('status', 'ready')
    ->accessCheck(FALSE)
    ->execute();

  // Load all the AMI sets.
  $entities = \Drupal::entityTypeManager()->getStorage('ami_set_entity')->loadMultiple($entities_nids);
  foreach ($entities as $entity) {
    $entity->setStatus(amiSetEntity::STATUS_READY);
    $entity->save();
  }

}

/**
 * Update ami_update_10161 - Updates Deprecated File Validators,
 * adds new AMI Field for last sent config and removes unused report_file.
 */
function ami_update_10161() {
  // Holds the last sent-to-Processing config
  $storage_definition = BaseFieldDefinition::create('strawberryfield_field')
    ->setLabel(t('Last Config used to send to processing'))
    ->setTranslatable(FALSE)
    ->setDisplayOptions('view', [
      'label' => 'hidden',
      'type' => 'strawberry_default_formatter',
      'weight' => 1,
    ])
    ->setDisplayConfigurable('form', FALSE)
    ->setDisplayConfigurable('view', TRUE)
    ->setRequired(FALSE)
    ->addConstraint('valid_strawberry_json');

  \Drupal::entityDefinitionUpdateManager()->installFieldStorageDefinition('last_processed_config', 'ami_set_entity', 'ami', $storage_definition);
  // Remove Report File. We are using monolog, not attaching to the entity.
  $report_file_definition = \Drupal::entityDefinitionUpdateManager()->getFieldStorageDefinition('report_file', 'ami_set_entity');
  \Drupal::entityDefinitionUpdateManager()->uninstallFieldStorageDefinition($report_file_definition);

  // Update File validators for Drupal >= 10.2 and required in >= 11.3
  // @see https://www.drupal.org/node/3363700
  $validatorszip = [
    'FileExtension' => [
      'extensions' => 'zip'
    ],
    'FileSizeLimit' => [
      'fileLimit' => Environment::getUploadMaxSize()
    ]
  ];
  $validatorscsv = [
    'FileExtension' => [
      'extensions' => 'csv'
    ]
  ];

  $field_storage_definition_source_data = \Drupal::entityDefinitionUpdateManager()->getFieldStorageDefinition('source_data', 'ami_set_entity');
  $field_storage_definition_source_data->setSetting('upload_validators', $validatorscsv);
  $field_storage_definition_source_data->setDisplayOptions('form', [
    'type' => 'file',
    'description' => [
      'theme' => 'file_upload_help',
      'description' => t('Your Source Data for this Set')
    ]	,
    'settings' => [
      'upload_validators' => $validatorscsv,
    ],
    'weight' => -3,
  ]);
  \Drupal::entityDefinitionUpdateManager()->updateFieldStorageDefinition($field_storage_definition_source_data);

  $field_storage_definition_processed_data = \Drupal::entityDefinitionUpdateManager()->getFieldStorageDefinition('processed_data', 'ami_set_entity');
  $field_storage_definition_processed_data->setSetting('upload_validators', $validatorscsv);
  \Drupal::entityDefinitionUpdateManager()->updateFieldStorageDefinition($field_storage_definition_processed_data);


  $field_storage_definition_zip_file = \Drupal::entityDefinitionUpdateManager()->getFieldStorageDefinition('zip_file', 'ami_set_entity');
  $field_storage_definition_zip_file->setSetting('upload_validators', $validatorszip);

  $field_storage_definition_zip_file->setDisplayOptions('form', [
    'type' => 'file',
    'description' => [
      'theme' => 'file_upload_help',
      'description' => t('Zipped Source Files for this Set')
    ],
    'settings' => [
      'upload_validators' => $validatorszip,
    ],
    'weight' => -3,
  ]);
  \Drupal::entityDefinitionUpdateManager()->updateFieldStorageDefinition($field_storage_definition_zip_file);
}
/**
 * Update ami_update_10171 - Checks for pre-update AMI set CSV escaping,
 * If a CSV row attached to an AMI set that has escaped characters is found
 * The AMI set is marked as needing a suggested Update process.
 */
function ami_update_10171() {
  $to_be_reviewed = [];
  $entities_nids = \Drupal::entityQuery('ami_set_entity')
    ->condition('changed',  \Drupal::time()->getRequestTime())
    ->accessCheck(FALSE)
    ->execute();
  /** @var \Drupal\ami\Entity\amiSetEntity[] $entities */
  $entities = \Drupal::entityTypeManager()
    ->getStorage('ami_set_entity')
    ->loadMultiple($entities_nids);
  foreach ($entities as $ami_set_entity) {
    // Check first source data
    $csv_file_reference = $ami_set_entity->get('source_data')->getValue();
    if (isset($csv_file_reference[0]['target_id'])) {
      /** @var \Drupal\file\Entity\File $file */
      $file = \Drupal::entityTypeManager()->getStorage('file')->load(
          $csv_file_reference[0]['target_id']
        );
      $amiUtilityService = \Drupal::service('ami.utility');
      // To avoid adding a new field, we will use the actual updated date
      // as a check.
      $hasescaping = $amiUtilityService->csv_check_escaped($file);
      if ($hasescaping) {
        $to_be_reviewed[] = $ami_set_entity->id();
        $ami_set_entity->setStatus(amiSetEntity::STATUS_NEEDS_REVIEW);
      }
    }
    // Also check Processed data (LoD reconciliation)
    $csv_file_reference_processed = $ami_set_entity->get('processed_data')->getValue();
    if (isset($csv_file_reference_processed[0]['target_id'])) {
      /** @var \Drupal\file\Entity\File $file */
      $file = \Drupal::entityTypeManager()->getStorage('file')->load(
          $csv_file_reference_processed[0]['target_id']
        );
      $amiUtilityService = \Drupal::service('ami.utility');
      // To avoid adding a new field, we will use the actual updated date
      // as a check.
      $hasescaping = $amiUtilityService->csv_check_escaped($file);
      if ($hasescaping) {
        $to_be_reviewed[] = $ami_set_entity->id();
        $ami_set_entity->setStatus(amiSetEntity::STATUS_NEEDS_REVIEW);
      }
    }
  }
  if (!empty($to_be_reviewed)) {
    $to_be_reviewed = array_unique($to_be_reviewed);
    return t('Possible none-compliant, with RFC 4180, CSVs found in the following AMI set entities: @entities. All those wehre marked as "Needing Review", if you need to re-run them.',  [
      '@entities' => implode(', ',$to_be_reviewed)
    ]);
  }
  else {
    return t('Good! All your AMI set entity\'s CSVs seem to be RFC 4180 compliant!');
  }
}